name: Check OpenAPI Changes

on:
  schedule:
    - cron: "0 6-15 * * 1-5" # Runs every 2 hours from 8 AM to 6 PM Vilnius time (adjusted to UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  check-openapi-changes:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download OpenAPI Spec
        run: curl -o new_openapi.yaml ${{ vars.OPENAPI_SPEC }}

      - name: Calculate hash of OpenAPI Spec
        id: calculate_hash
        run: |
          NEW_HASH=$(sha256sum new_openapi.yaml | awk '{ print $1 }')
          echo "New hash: $NEW_HASH"
          echo "$NEW_HASH" > .openapi_hash

      - name: Check if hash has changed
        id: check_changes
        run: |
          if [ -f .openapi_hash ]; then
            OLD_HASH=$(cat .openapi_hash)
          else
            OLD_HASH=""
          fi
          NEW_HASH=$(cat .openapi_hash)
          if [ "$NEW_HASH" != "$OLD_HASH" ]; then
            echo "Hash has changed"
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "Hash has not changed"
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Commit and push new hash
        if: env.changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .openapi_hash
          git commit -m "Update OpenAPI hash"
          git push

      - name: Trigger API Generation Workflow
        if: env.changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "generate-api-and-release.yml",
              ref: "main"
            })