name: TST

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  tst:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Download OpenAPI Spec
        run: echo "Downloading OpenAPI spec from spec"